repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [ '--fix' ]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.4
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      # generate/update files first and in parallel (priority 1)
      - id: update-generated-types
        name: update generated types
        entry: uv run --active scripts/update-generated-types.py
        language: python
        pass_filenames: false
        priority: 1

      - id: update-json-schema
        name: update json schema
        entry: uv run --active scripts/update-json-schema.py
        language: python
        pass_filenames: false
        priority: 1

      - id: update-json-configs
        name: update json configs
        entry: uv run --active scripts/update-json-configs.py
        language: python
        pass_filenames: false
        priority: 1

      - id: ty-check
        name: ty check
        entry: uv run --active ty check --color never --no-progress
        language: python
        pass_filenames: false
